title: 'Raoul Zander :: Portfolio'
author:
  name: 'Raoul Zander'
taxonomies:
  - indexTag
  - tag
  - typeOfWork
  - language
  - promoted
  - series
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
